INSERT INTO VRSTANEK(IDVN,NAZIVV) VALUES(1,'Kuca');
INSERT INTO VRSTANEK(IDVN,NAZIVV) VALUES(2,'Stan');
INSERT INTO VRSTANEK(IDVN,NAZIVV) VALUES(3,'Garaza');
INSERT INTO VRSTANEK(IDVN,NAZIVV) VALUES(4,'Poslovni prostor');
COMMIT;

INSERT INTO VLASNIK(IDV,IMEV,PRZV,VRSTAV)VALUES('V1','Marko','Markovic','FIZICKO');
INSERT INTO VLASNIK(IDV,IMEV,PRZV,VRSTAV)VALUES('V2','Ana','Antic','PRAVNO');
INSERT INTO VLASNIK(IDV,IMEV,PRZV,VRSTAV)VALUES('V3','Milica','Mandic','FIZICKO');
INSERT INTO VLASNIK(IDV,IMEV,PRZV,VRSTAV)VALUES('V4','Nemanja','Nemanjic','FIZICKO');
INSERT INTO VLASNIK(IDV,IMEV,PRZV,VRSTAV)VALUES('V5','Danica','Danicic','PRAVNO');
INSERT INTO VLASNIK(IDV,IMEV,PRZV,VRSTAV)VALUES('V6','Milan','Majstorovic','FIZICKO');
COMMIT;

INSERT INTO NEKRETNINA(IDN,IDV,KVD,ADR,BRNEK,BRST,OPSTINA,IDVN)VALUES(1,'V1',56,'Velebitska',12,106,'Novi Sad',2);
INSERT INTO NEKRETNINA(IDN,IDV,KVD,ADR,BRNEK,BRST,OPSTINA,IDVN)VALUES(2,'V1',206,'Balzakova',12,NULL,'Petrovaradin',1);
INSERT INTO NEKRETNINA(IDN,IDV,KVD,ADR,BRNEK,BRST,OPSTINA,IDVN)VALUES(3,'V2',325,'Zlatne grede',65,NULL,'Novi Sad',4);
INSERT INTO NEKRETNINA(IDN,IDV,KVD,ADR,BRNEK,BRST,OPSTINA,IDVN)VALUES(4,'V2',284,'Mileticeva',39,NULL,'Novi Sad',4);
INSERT INTO NEKRETNINA(IDN,IDV,KVD,ADR,BRNEK,BRST,OPSTINA,IDVN)VALUES(5,'V6',72,'Strazilovska',41,58,'Petrovaradin',2);
INSERT INTO NEKRETNINA(IDN,IDV,KVD,ADR,BRNEK,BRST,OPSTINA,IDVN)VALUES(6,'V6',125,'Pasterova',6,NULL,'Petrovaradin',1);
INSERT INTO NEKRETNINA(IDN,IDV,KVD,ADR,BRNEK,BRST,OPSTINA,IDVN)VALUES(7,'V3',48,'Fruskogorska',9,158,'Novi Sad',2);
INSERT INTO NEKRETNINA(IDN,IDV,KVD,ADR,BRNEK,BRST,OPSTINA,IDVN)VALUES(8,'V4',63,'Sutjeska',87,84,'Novi Sad',2);
COMMIT;

INSERT INTO PORESKAKARTICA(IDK,IDV,SALDO,DUG,KAMATA)VALUES(1,'V1',102.56,0,0);
INSERT INTO PORESKAKARTICA(IDK,IDV,SALDO,DUG,KAMATA)VALUES(2,'V2',-15789,13456,2333);
INSERT INTO PORESKAKARTICA(IDK,IDV,SALDO,DUG,KAMATA)VALUES(3,'V3',250,0,0);
INSERT INTO PORESKAKARTICA(IDK,IDV,SALDO,DUG,KAMATA)VALUES(4,'V4',1500,0,0);
INSERT INTO PORESKAKARTICA(IDK,IDV,SALDO,DUG,KAMATA)VALUES(5,'V5',-567.45,122.36,445.09);
INSERT INTO PORESKAKARTICA(IDK,IDV,SALDO,DUG,KAMATA)VALUES(6,'V6',-12012,11000,1012);
COMMIT;