CREATE TABLE VLASNIK(
  IDV VARCHAR2(8) NOT NULL,
  IMEV VARCHAR2(20) NOT NULL,
  PRZV VARCHAR2(20) NOT NULL,
  VRSTAV VARCHAR2(12) NOT NULL,
  CONSTRAINT PK_VLASNIK PRIMARY KEY (IDV),
  CONSTRAINT CH_VRSTAV CHECK (VRSTAV IN ('FIZICKO', 'PRAVNO'))
);

CREATE TABLE VRSTANEK(
  IDVN INTEGER NOT NULL,
  NAZIVV VARCHAR2(40) NOT NULL,
  CONSTRAINT PK_VRSTANEK PRIMARY KEY (IDVN)
);

CREATE TABLE NEKRETNINA(
  IDN INTEGER NOT NULL,
  IDV VARCHAR2(8) NOT NULL,
  KVD DECIMAL(10,2) NOT NULL,
  ADR VARCHAR2(100) NOT NULL,
  BRNEK INTEGER NOT NULL,
  BRST INTEGER,
  OPSTINA VARCHAR2(40) NOT NULL,
  IDVN INTEGER NOT NULL,
  CONSTRAINT PK_NEKRETNINA PRIMARY KEY(IDN),
  CONSTRAINT FK_NEKRETNINA_VRSTANEK FOREIGN KEY (IDVN) REFERENCES VRSTANEK(IDVN),
  CONSTRAINT FK_NEKRETNINA_VLASNIK FOREIGN KEY (IDV) REFERENCES VLASNIK (IDV)
);

CREATE TABLE PORESKAKARTICA(
  IDK INTEGER NOT NULL,
  IDV VARCHAR(13) NOT NULL,
  SALDO DECIMAL (10,2) NOT NULL,
  DUG DECIMAL (10,2) NOT NULL,
  KAMATA DECIMAL (10,2),
  CONSTRAINT PK_KARTICA PRIMARY KEY(IDK),
  CONSTRAINT FK_KARTICA_VLASNIK FOREIGN KEY (IDV) REFERENCES VLASNIK(IDV)
);