INSERT INTO GRAD(IDG, NAZIVG, DRZ) VALUES ('BG', 'Belgrade', 'RS');
INSERT INTO GRAD(IDG, NAZIVG, DRZ) VALUES ('AM', 'Amterdam', 'NL');
INSERT INTO GRAD(IDG, NAZIVG, DRZ) VALUES ('TO', 'Tokyo', 'JP');
INSERT INTO GRAD(IDG, NAZIVG, DRZ) VALUES ('MO', 'Moscow', 'RU');
INSERT INTO GRAD(IDG, NAZIVG, DRZ) VALUES ('BE', 'Berlin', 'DE');
COMMIT;

INSERT INTO AERODROM(IDA, NAZIVA, GRADA) VALUES ('BEG', 'Nikola Tesla', 'BG');
INSERT INTO AERODROM(IDA, NAZIVA, GRADA) VALUES ('AMS', 'Schiphol', 'AM');
INSERT INTO AERODROM(IDA, NAZIVA, GRADA) VALUES ('TXL', 'Tegel', 'BE');
INSERT INTO AERODROM(IDA, NAZIVA, GRADA) VALUES ('HND', 'Haneda', 'TO');
INSERT INTO AERODROM(IDA, NAZIVA, GRADA) VALUES ('NRT', 'Narita', 'TO');
INSERT INTO AERODROM(IDA, NAZIVA, GRADA) VALUES ('SVO', 'Sheremetyevo', 'MO');
COMMIT;

INSERT INTO PREVOZNIK(IDP, NAZIVP, GRADP, BRAVFLT) VALUES ('LH', 'Lufthansa', 'BE', 275);
INSERT INTO PREVOZNIK(IDP, NAZIVP, GRADP, BRAVFLT) VALUES ('JU', 'air Serbia', 'BG', 21);
INSERT INTO PREVOZNIK(IDP, NAZIVP, GRADP, BRAVFLT) VALUES ('SU', 'Aeroflot', 'MO', 170);
INSERT INTO PREVOZNIK(IDP, NAZIVP, GRADP, BRAVFLT) VALUES ('JL', 'Japan Airlines', 'TO', 158);
INSERT INTO PREVOZNIK(IDP, NAZIVP, GRADP, BRAVFLT) VALUES ('MP', 'martinair', 'AM', 1);
COMMIT;

INSERT INTO RUTA(IDR, PREV, POLAZ, ODRED, CENA, VALUTA) 
VALUES ('R1', 'LH', 'NRT', 'TXL', 550, 'EUR');
INSERT INTO RUTA(IDR, PREV, POLAZ, ODRED, CENA, VALUTA) 
VALUES ('R2', 'LH', 'HND', 'TXL', 330, 'EUR');
INSERT INTO RUTA(IDR, PREV, POLAZ, ODRED, CENA, VALUTA) 
VALUES ('R3', 'LH', 'TXL', 'SVO', 220, 'EUR');
INSERT INTO RUTA(IDR, PREV, POLAZ, ODRED, CENA, VALUTA) 
VALUES ('R4', 'LH', 'HND', 'SVO', 550, 'EUR');
INSERT INTO RUTA(IDR, PREV, POLAZ, ODRED, CENA, VALUTA) 
VALUES ('R5', 'SU', 'TXL', 'SVO', 380, 'USD');
INSERT INTO RUTA(IDR, PREV, POLAZ, ODRED, CENA, VALUTA) 
VALUES ('R6', 'SU', 'NRT', 'SVO', 350, 'USD');
INSERT INTO RUTA(IDR, PREV, POLAZ, ODRED, CENA, VALUTA) 
VALUES ('R7', 'SU', 'SVO', 'BEG', 300, 'USD');
INSERT INTO RUTA(IDR, PREV, POLAZ, ODRED, CENA, VALUTA) 
VALUES ('R8', 'JU', 'SVO', 'BEG', 280, 'EUR');
INSERT INTO RUTA(IDR, PREV, POLAZ, ODRED, CENA, VALUTA) 
VALUES ('R9', 'JU', 'BEG', 'AMS', 200, 'CHF');
INSERT INTO RUTA(IDR, PREV, POLAZ, ODRED, CENA, VALUTA) 
VALUES ('R10', 'JL', 'SVO', 'NRT', 800, 'USD');
INSERT INTO RUTA(IDR, PREV, POLAZ, ODRED, CENA, VALUTA) 
VALUES ('R11', 'JL', 'TXL', 'NRT', 900, 'USD');
COMMIT;