DROP TABLE RUTA;
DROP TABLE PREVOZNIK;
DROP TABLE AERODROM;
DROP TABLE GRAD;

CREATE TABLE GRAD (
  IDG VARCHAR2(2) NOT NULL,
  NAZIVG VARCHAR2(128) NOT NULL,
  DRZ VARCHAR2(2) NOT NULL,
  CONSTRAINT PK_GRAD PRIMARY KEY (IDG)
);

CREATE TABLE AERODROM (
  IDA VARCHAR2(3) NOT NULL,
  NAZIVA VARCHAR2(128) NOT NULL,
  GRADA VARCHAR2(2),
  CONSTRAINT PK_AERODROM PRIMARY KEY (IDA),
  CONSTRAINT FK_AERODROM_GRAD FOREIGN KEY (GRADA) REFERENCES GRAD (IDG)
);

CREATE TABLE PREVOZNIK (
  IDP VARCHAR2(2) NOT NULL,
  NAZIVP VARCHAR2(128) NOT NULL,
  GRADP VARCHAR2(2),
  BRAVFLT INTEGER,
  CONSTRAINT PK_PREVOZNIK PRIMARY KEY (IDP),
  CONSTRAINT FK_PREVOZNIK_GRAD FOREIGN KEY (GRADP) REFERENCES GRAD (IDG)
);

CREATE TABLE RUTA (
  IDR VARCHAR2(15) NOT NULL,
  PREV VARCHAR2(128) NOT NULL,
  POLAZ VARCHAR2(3) NOT NULL,
  ODRED VARCHAR2(3) NOT NULL,
  CENA DECIMAL(10,2),
  VALUTA VARCHAR(3) NOT NULL,
  CONSTRAINT PK_RUTA PRIMARY KEY (IDR),
  CONSTRAINT FK_RUTA_POLAZ FOREIGN KEY (POLAZ) REFERENCES AERODROM (IDA),
  CONSTRAINT FK_RUTA_ODRED FOREIGN KEY (ODRED) REFERENCES AERODROM (IDA),
  CONSTRAINT FK_RUTA_PREVOZNIK FOREIGN KEY (PREV) REFERENCES PREVOZNIK (IDP),
  CONSTRAINT CH_VALUTA CHECK (VALUTA IN ('USD', 'EUR', 'CHF'))
);