-- UPITI NAD JEDNOM TABELOM
SELECT *FROM RADNIK;
SELECT *FROM PROJEKAT;
SELECT *FROM RADPROJ;
SELECT IME, PRZ FROM RADNIK;

-- DISTINCT 
SELECT DISTINCT IME FROM RADNIK;

-- WHERE USLOV
SELECT MBR, IME, PRZ, PLT FROM RADNIK 
    WHERE PLT > 25000;

-- IZLISTATI GODIŠNJU PLATU SVAKOG RADNIKA
SELECT MBR, IME, PRZ AS PREZIME, PLT * 12 AS PLATA FROM RADNIK;

-- IZLISTATI MBR, IME, PRZ RADNIKA KOJI NEMAJU ŠEFA
SELECT MBR, IME, PRZ AS PREZIME FROM RADNIK 
    WHERE SEF IS NULL;

-- IZLISTATI MBR, IME, PRZ RADNIKA ČIJA JE PLATA IZMEĐU 20000 I 24000 DINARA
SELECT MBR, IME, PRZ AS PREZIME, PLT AS PLATA FROM RADNIK 
    WHERE PLT BETWEEN 20000 AND 24000;

-- IZLISTATI IME, PRZ, GOD RADNIKA ROĐENIH IZMEĐU 1953 I 1975
SELECT IME, PRZ AS PREZIME, GOD AS "GODINA RODJENJA" FROM RADNIK
    WHERE GOD BETWEEN '01-JAN-1953' AND '31-DEC-1975';

-- IZLISTATI IME, PRZ, GOD RADNIKA KOJI NISU ROĐENI IZMEĐU 1953 I 1975
SELECT IME, PRZ AS PREZIME, GOD AS "GODINA RODJENJA" FROM RADNIK
    WHERE GOD NOT BETWEEN '01-JAN-1953' AND '31-DEC-1975';

-- IZLISTATI MBR, IME, PRZ RADNIKA ČIJE PREZIME POČINJE NA SLOVO M
SELECT MBR, IME, PRZ AS PREZIME FROM RADNIK
    WHERE PRZ LIKE 'M%';

-- IZLISTATI MBR, IME, PRZ RADNIKA ČIJE PREZIME NE POČINJE SLOVOM A
SELECT MBR, IME, PRZ AS PREZIME FROM RADNIK
    WHERE IME NOT LIKE 'A%';

-- IZLISTATI MBR, IME, PRZ RADNIKA ČIJE IME SADRŽI SLOVO a NA DRUGOJ POZICIJI
SELECT MBR, IME, PRZ AS PREZIME FROM RADNIK
    WHERE IME LIKE '_a%';

-- IZLISTATI IMENA RADNIKA KOJA POČINJU NA SLOVO E. IMENA NE BI TREBALO DA SE PONAVLJAJU
SELECT DISTINCT IME FROM RADNIK
    WHERE IME LIKE 'E%';

-- IZLISTATI RADNIKE KOJI U SVOM IMENU IMAJU SLOVO E (e)
SELECT MBR, IME, PRZ AS PREZIME FROM RADNIK
    WHERE IME LIKE '%e%' OR
          IME LIKE '%E%';

-- IZLISTATI MATIČNE BROJEVE RADNIKA KOJI RADE NA PROJEKTIMA SA ŠIFROM 10, 20 ILI 30
SELECT DISTINCT MBR FROM RADPROJ
    WHERE SPR IN(10, 20, 30);

-- IZLISTATI MATIČNE BROJEVE RADNIKA KOJI RADE NA PROJEKTU SA ŠIFROM 10 ILI RADE 2, 4, ILI 6 SATI
SELECT DISTINCT MBR FROM RADPROJ
    WHERE BRC IN(2, 4, 6) OR SPR = '10';

-- IZLISTATI MATIČNE BROJEVE RADNIKA KOJI SE NE ZOVU ANA ILI SANJA.
SELECT MBR, IME, PRZ AS PREZIME FROM RADNIK
    WHERE IME NOT IN('Ana', 'Sanja');

-- PRIKAZATI RADNIKE KOJI IMAJU ŠEFA SORTIRANO PO PREZIMENU
SELECT MBR, IME, PRZ AS PREZIME, PLT AS PLATA FROM RADNIK
    WHERE SEF IS NOT NULL
    ORDER BY PRZ ASC;

-- PRIKAZATI MATIČNE BROJEVE, IMENA, PREZIMENA I PLATE RADNIKA, PO OPADAJUĆEM REDOSLEDU IZNOSA PLATE
SELECT MBR, IME, PRZ AS PREZIME, PLT AS PLATA FROM RADNIK
    ORDER BY PLATA DESC;

-- PRIKAZATI MATIČNE BROJEVE, SPOJENA (KONKATENIRANA) IMENA I PREZIMENA RADNIKA, KAO I PLATE, UVEĆANE ZA 17%
SELECT MBR, IME || ' ' || PRZ "IME I PREZIME", PLT * 1.17 AS PLATA FROM RADNIK;

-- PRIKAZATI RADNIKE ČIJE PREZIME SADRŽI IME. NA PRIMER MARKO MARKOVIĆ, 
-- ILI DJORDJE KARADJORDJEVIC – FUNKCIJE UPPER, LOWER
SELECT *FROM RADNIK
    WHERE LOWER(PRZ) LIKE '%' || LOWER(IME) || '%';

-- PRIKAZATI MATIČNE BROJEVE RADNIKA, IMENA I PREZIMENA I PLATU RADNIKA KOJI SE ZOVU PERA ILI MOMA
SELECT MBR, IME, PRZ AS PREZIME, PLT AS PLATA FROM RADNIK
    WHERE IME = ANY('Pera', 'Moma');

-- PRIKAZATI MATIČNE BROJEVE RADNIKA, IMENA I PREZIMENA I 
-- PLATU RADNIKA KOJI SE NE ZOVU PERA ILI MOMA
SELECT MBR, IME, PRZ AS PREZIME, PLT AS PLATA FROM RADNIK
    WHERE IME != ANY('Pera', 'Moma');

-- PRIKAZATI MATIČNE BROJEVE RADNIKA, KAO I PLATE, UVEĆANE ZA NULL VREDNOST
SELECT MBR, PLT + NULL FROM RADNIK;

-- PRIKAZATI MATIČNE BROJEVE RADNIKA, KAO I PLATE, UVEĆANE ZA GODIŠNJU PREMIJU
SELECT MBR, PLT + PRE FROM RADNIK;

-- PRIKAZATI MATIČNE BROJEVE RADNIKA, KAO I PLATE, UVEĆANE ZA GODIŠNJU PREMIJU. 
-- UKOLIKO ZA NEKOG RADNIKA VREDNOST PREMIJE NE POSTOJI, SMATRATI DA ONA IZNOSI 0
SELECT MBR, PLT + NVL(PRE, 0) AS "PLATA SA PREMIJOM" FROM RADNIK;

--                            FUNKCIJA COUNT
--   COUNT(*)                   – VRAĆA UKUPAN BROJ SELEKTOVANIH TORKI
-- • COUNT(         <OBELEŽJE>) – VRAĆA UKUPAN BROJ SELEKTOVANIH TORKI, 
--                                ZA KOJE VREDNOST <OBELEŽJA> NIJE NULA VREDNOST
-- • COUNT(DISTINCT <OBELEŽJE>) – VRAĆA UKUPAN BROJ RAZLIČITIH TORKI, ZA KOJE
--                                VREDNOST <OBELEŽJA> NIJE NULA VREDNOST

-- KOLIKO IMA RADNIKA?
SELECT COUNT(*) AS "BROJ RANDIKA" FROM RADNIK;

-- KOLIKO IMA ŠEFOVA?
SELECT COUNT(DISTINCT SEF) "BROJ SEFOVA" FROM RADNIK;

-- PRIKAZATI MINIMALNU I MAKSIMALNU PLATU RANDIKA
SELECT MIN(PLT) "MINIMALNA PLATA", MAX(PLT) "MAKSIMALNA PLATA" FROM RADNIK;

-- PRIKAZATI BROJ RADNIKA I UKUPNU MESEČNU PLATU SVIH RADNIKA
SELECT COUNT(*) AS "BROJ RADNIKA", SUM(PLT) AS "UKUPNA MESECNA PLATA" FROM RADNIK;

-- PRIKAZATI BROJ RADNIKA, PROSEČNU PLATU I UKUPNU GODIŠNJU PLATU SVIH RADNIKA
SELECT COUNT(*) "BROJ RADNIKA", ROUND(AVG(PLT), 0) AS "PROSECNA PLATA", 12 * SUM(PLT) AS "GODISNJA PLATA" FROM RADNIK;

-- PRIKAZATI UKUPNU PREMIJU SVIH RADNIKA ČIJI JE MATIČNI BROJ VEĆI OD 100
SELECT SUM(PRE) FROM RADNIK
    WHERE MBR > 100;

-- PRIKAZATI PROSEČNU PLATU SVIH RADNIKA POMNOŽENU SA KOREN IZ 2 (1,41) ZAOKRUŽENO NA DVE DECIMALE
SELECT ROUND(AVG(PLT * 1.41), 2) AS "PROSECNA PLATA * 1.41" FROM RADNIK;

-- SELECT NAREDBA U LISTI TABELA
SELECT * FROM (SELECT MBR, IME FROM RADNIK);

-- PRIKAZATI 10 RADNIKA KOJI IMAJU NAJVEĆU PLATU, SORTIRANIH PO PLATI U OPADAJUĆEM REDOSLEDU
SELECT MBR, PLT, ROWNUM FROM
    (SELECT *FROM RADNIK ORDER BY PLT DESC)
    WHERE ROWNUM <= 10;

-- PRIKAZATI ZA SVAKOG RADNIKA RED KOJI SADRŽI NJEGOVU PLATU, PROSEČNU PLATU I APSOLUTNU
-- (ABS) RAZLIKU PROSEČNE PLATE I NJEGOVE PLATE.
SELECT PLT AS PLATA,
    (SELECT ROUND(AVG(PLT), 2) FROM RADNIK) AS "PROSECNA PLATA",
    ABS((SELECT ROUND(AVG(PLT), 2) FROM RADNIK) - PLT) AS "RAZLIKA"
    FROM RADNIK;