-- DODAVANJE NOVE TORKE
INSERT INTO RADNIK (MBR, IME, PRZ, PLT, SEF, GOD) 
    VALUES (201, 'ANA', 'SAVIC', 30000, NULL, '18-AUG-71');

-- DODAVANJE NOVE TORKE
INSERT INTO PROJEKAT (SPR, NAP, RUK)
    VALUES (90, 'P1', 201);

-- DODAVANJE NOVE TORKE
INSERT INTO RADPROJ (MBR, SPR, BRC)
    VALUES (201, 90, 5);

-- BRISANJE POSTOJEĆIH TORKI
DELETE RADNIK;

-- BRISANJE POSTOJEĆIH TORKI
DELETE RADNIK WHERE MBR = 701;

-- MODIFIKACIJA POSTOJEĆIH TORKI
UPDATE RADNIK
    SET PLT = PLT * 1.2;
    
-- MODIFIKACIJA POSTOJEĆIH TORKI
UPDATE RADNIK
    SET PLT = PLT * 1.2
    WHERE MBR = 201;

-- KREIRATI TABELU FAZE_PROJEKTA
CREATE TABLE FAZE_PROJEKTA (
    SPR INTEGER,
    SFP INTEGER,
    RUKFP INTEGER,
    NAFP VARCHAR2(35) UNIQUE,
    DATP DATE,

    CONSTRAINT FP_PK PRIMARY KEY (SPR, SFP),
    CONSTRAINT FP_SPR_FK FOREIGN KEY (SPR) REFERENCES PROJEKAT(SPR)
);

-- DODATI DATUM ZAVRSETKA FAZE PROJEKTA
ALTER TABLE FAZE_PROJEKTA
    ADD DATZ DATE;

-- MODIFIKOVATI KOLONU TAKO DA PODRAZUMEVANA VREDNOST ZA DATZ BUDE DANASNJI DATUM
ALTER TABLE FAZE_PROJEKTA
    MODIFY DATZ DATE DEFAULT SYSDATE;

-- DODATI OGRANICENJE DA DATUM ZAVRSETKA BUDE VECI OD DATUMA POCETKA
ALTER TABLE FAZE_PROJEKTA
    ADD CONSTRAINT FP_DAT_CH CHECK (DATZ >= DATP);

-- OBRISATI KOLONU DATZ
ALTER TABLE FAZE_PROJEKTA
    DROP CONSTRAINT FP_DAT_CH;

ALTER TABLE FAZE_PROJEKTA
    DROP COLUMN DATZ;

-- OBRISATI TABELU FAZE_PROJEKTA
DROP TABLE FAZE_PROJEKTA;

-- PRIKAZATI RADNIKE ANGAZOVANE NA PROJEKTU I BROJ DRUGIH RADNIKA
-- KOJI SU NA ISTOM PROJEKTU
WITH BROJ_RADNIKA_PO_PROJEKTU AS (SELECT SPR, COUNT(MBR) - 1 AS "BROJ RADNIKA" FROM RADPROJ GROUP BY SPR)
SELECT R.MBR, IME, PRZ AS PREZIME, RP.SPR AS "SIFRA PROJEKTA", "BROJ RADNIKA" 
    FROM RADNIK R, RADPROJ RP, BROJ_RADNIKA_PO_PROJEKTU B
    WHERE R.MBR = RP.MBR AND
          RP.SPR = B.SPR;

-- PRIKAZATI RADNIKE ANGAZOVANE NA PROJEKTU I BROJ DRUGIH RADNIKA
-- I UDEO U UKUPNOM BROJU CASOVA NA TOM PROJEKTU
WITH RADNIKA_PO_PROJEKTU AS (SELECT SPR, SUM(BRC) "SUMA" FROM RADPROJ GROUP BY SPR)
SELECT R.MBR, IME, PRZ AS PREZIME, RP.SPR AS "SIFRA PROJEKTA", 
      "SUMA", ROUND(RP.BRC / SUMA * 100) || '%' AS "UDEO U PROCENTIMA"
    FROM RADNIK R, RADPROJ RP, RADNIKA_PO_PROJEKTU B
    WHERE R.MBR = RP.MBR AND
          RP.SPR = B.SPR;

-- PRIKAZATI RUKOVODIOCE PROJEKATA KAO I UKUPAN BROJ RADNIKA
-- KOJIMA RUKOVODE NA PROJEKTIMA
SELECT P.RUK, IME, PRZ AS PREZIME, COUNT(RP.MBR) AS "RADE NA PROJEKTU" FROM PROJEKAT P, RADNIK R, RADPROJ RP
    WHERE RUK = R.MBR AND 
          P.SPR = RP.SPR
    GROUP BY P.RUK, IME, PRZ;

-- NAPRAVITI POGLED KOJI CE ZA SVE RADNIKE PRIKAZATI NJIHOVA IMENA
-- PREZIMENA, I PLATU
CREATE OR REPLACE VIEW RADNICI_SA_PLATOM AS
    (SELECT MBR, IME, PRZ, PLT * 12 AS "GODISNJA PLATA" FROM RADNIK);

-- PRIKAZATI POGLED ZA SVE RADNIKE
SELECT *FROM RADNICI_SA_PLATOM;

-- NAPRAVITI POGLED KOJI CE ZA SVE RADNIKE PRIKAZATI MBR I
-- I UKUPAN BROJ SATI ANGAZOVANJA RADNIKA NA PROJEKTIMA NA KOJIMA RADI
CREATE OR REPLACE VIEW ANGAZOVANJE_RADNIKA AS
    SELECT R.MBR, IME, PRZ AS PREZIME, NVL(SUM(BRC), 0) AS SATI FROM RADNIK R, RADPROJ RP
        WHERE R.MBR = RP.MBR(+)
        GROUP BY R.MBR, IME, PRZ;

-- NAPRAVITI POGLED ZA SEFOVE KORISTECI PRETHODNI POGLED
SELECT AR.MBR, AR.IME, AR.PREZIME, COUNT(R.MBR) AS RADNIKA FROM ANGAZOVANJE_RADNIKA AR, RADNIK R
    WHERE AR.MBR = R.SEF
    GROUP BY AR.MBR, AR.IME, AR.PREZIME, AR.SATI;

-- DUMMY TABLE
SELECT SYSDATE FROM SYS.DUAL;

-- SUBSTRING
SELECT SUBSTR('UVOD U BAZE PODATAKA', 8, 4) FROM SYS.DUAL;

-- BROJ U STRING
SELECT TO_CHAR(10) FROM SYS.DUAL;