-- IZLISTATI NAZIVE PROJEKATA NA KOJIMA SE RADI VISE OD 15 SATI
SELECT P.SPR, NAP, SUM(BRC) FROM PROJEKAT P, RADPROJ RP
    WHERE P.SPR = RP.SPR
    GROUP BY P.SPR, NAP
    HAVING SUM(BRC) > 15;

-- IZLISTATI NAZIVE I SIFRE PROJEKATA NA KOJIMA JE AVG ANGAZOVANJE
-- VECE OD AVG ANGAZOVANJA NA SVIM PROJEKTIMA
SELECT P.SPR, NAP, AVG(BRC) FROM PROJEKAT P, RADPROJ RP
    WHERE P.SPR = RP.SPR
    GROUP BY P.SPR, NAP
    HAVING AVG(BRC) > (SELECT AVG(BRC) FROM RADPROJ);

-- IZLISTATI NAZIVE I SIFRE PROJEKATA SA NAJVECIM PROSECNIM ANGAZOVANJE
SELECT P.SPR, NAP, AVG(BRC) FROM PROJEKAT P, RADPROJ RP
    WHERE P.SPR = RP.SPR
    GROUP BY P.SPR, NAP
    HAVING AVG(BRC) =
        (SELECT PROSEK FROM (SELECT AVG(BRC) AS PROSEK FROM RADPROJ RP
            GROUP BY RP.SPR
            ORDER BY AVG(BRC) DESC) WHERE ROWNUM = 1);

-- IZLISTATI NAZIVE I SIFRE PROJEKATA SA NAJVECIM PROSECNIM ANGAZOVANJE
SELECT P.SPR, NAP, AVG(BRC) FROM PROJEKAT P, RADPROJ RP
    WHERE P.SPR = RP.SPR
    GROUP BY P.SPR, NAP
    HAVING AVG(BRC) = (SELECT MAX(AVG(BRC)) FROM RADPROJ GROUP BY SPR);

-- PRIKAZATI MBR, IME, PRZ, PLT RADNIKA KOJI ZARADJUJU VISE OD
-- RADNIKA SA SIFROM 40
SELECT MBR, IME, PRZ AS PREZIME, PLT AS PLATA FROM RADNIK
    WHERE PLT > (SELECT PLT FROM RADNIK WHERE MBR = 40);

--PRIKAZATI MBR, IME, PRZ, PLT RADNIKA KOJI ZARADJUJU VISE OD
-- RADNIKA SA SIFROM 40
SELECT R.MBR, R.IME, R.PRZ AS PREZIME, R.PLT AS PLATA FROM RADNIK R, RADNIK RM
    WHERE RM.MBR = 40 AND R.PLT > RM.PLT;

-- PRIKAZATI MBR, IME, PRZ, PLT RADNIKA CIJI JE BROJ SATI ANGAZOVANJA
-- NA NEKOM PROJEKTU VECI OD PROSECNOG BROJA SATI ANGAZOVANJA NA TOM PROJEKTU
SELECT R.MBR, IME, PRZ AS PREZIME, PLT AS PLATA, SPR, BRC AS SATI FROM RADNIK R, RADPROJ RP
    WHERE R.MBR = RP.MBR AND BRC > (SELECT AVG(BRC) FROM RADPROJ WHERE SPR = RP.SPR);

-- KO JE NAJSTARIJI RADNIK UPOTREBOM EXISTS
SELECT *FROM RADNIK R
    WHERE NOT EXISTS (SELECT *FROM RADNIK WHERE GOD < R.GOD);

-- IZLISTATI RADNIKE KOJI NE RADE NI NA JEDNOM PROJEKTU
SELECT MBR, IME, PRZ FROM RADNIK R
    WHERE NOT EXISTS (SELECT *FROM RADPROJ RP WHERE R.MBR = RP.MBR);

-- KO JE NAJMLADJI RUKOVODILAC PROJEKTA
SELECT *FROM RADNIK WHERE MBR IN (SELECT DISTINCT RUK FROM PROJEKAT) AND 
    GOD = (SELECT MAX(GOD) FROM RADNIK 
                WHERE MBR IN (SELECT DISTINCT RUK FROM PROJEKAT));

-- KO JE NAJMLADJI RUKOVODILAC PROJEKTA
SELECT DISTINCT RUK, IME, PRZ, GOD FROM PROJEKAT P, RADNIK R
    WHERE RUK = R.MBR AND GOD = (SELECT MAX(GOD) FROM PROJEKAT P, RADNIK R 
                                     WHERE RUK = R.MBR);

-- KO JE NAJMLADJI RUKOVODILAC PROJEKTA EXISTS
SELECT DISTINCT RUK, IME, PRZ, GOD FROM PROJEKAT P, RADNIK R
    WHERE RUK = R.MBR AND
    NOT EXISTS (SELECT MBR FROM RADNIK R1, PROJEKAT P1 
                    WHERE R1.MBR = P1.RUK AND R1.GOD > R.GOD);

-- IZLISTATI MBR, IME, PRZ RADNIKA KOJI RADE NA PROJEKTU SA SIFROM
-- 20 ILI IM JE PLATA VECA OD PROSECNE
SELECT MBR, IME, PRZ AS PREZIME FROM RADNIK
    WHERE MBR IN (SELECT MBR FROM RADPROJ WHERE SPR = 20) OR 
          PLT > (SELECT AVG(PLT) FROM RADNIK);

-- IZLISTATI MBR, IME, PRZ RADNIKA KOJI RADE NA PROJEKTU SA SIFROM
-- 20 ILI IM JE PLATA VECA OD PROSECNE
SELECT MBR, IME, PRZ AS PREZIME FROM RADNIK
    WHERE MBR IN (SELECT MBR FROM RADPROJ WHERE SPR = 20)
    UNION
SELECT MBR, IME, PRZ AS PREZIME FROM RADNIK
    WHERE PLT > (SELECT AVG(PLT) FROM RADNIK);

-- INNER JOIN V1
SELECT RADNIK.MBR, IME, PRZ AS PREZIME FROM RADNIK, RADPROJ
    WHERE RADNIK.MBR = RADPROJ.MBR;

-- INNER JOIN V2
SELECT RADNIK.MBR, IME, PRZ AS PREZIME FROM RADNIK INNER JOIN RADPROJ
    ON RADNIK.MBR = RADPROJ.MBR;

-- NATURAL JOIN (SPAJAJU SE PO OBELEZJIMA ISTOG NAZIVA)
SELECT MBR, IME, PRZ AS PREZIME FROM RADNIK NATURAL JOIN RADPROJ;

-- PRIKAZATI MBR, IME, PRZ SVIH RADNIKA I NAZIVA PROJEKATA KOJIMA RUKOVODE
SELECT RADNIK.MBR, IME, PRZ AS PREZIME, NAP AS "NAZIV PROJEKTA" FROM RADNIK 
    INNER JOIN PROJEKAT
    ON RADNIK.MBR = PROJEKAT.RUK;

-- PRIKAZATI MBR, IME, PRZ SVIH RADNIKA I NAZIVA PROJEKATA KOJIMA RUKOVODE
-- UKOLIKO RADNIK NE RUKOVODI NIJEDNIM PROJEKTOM NAPISATI DA ON NE RUKOVODI PROJEKTOM
SELECT RADNIK.MBR, IME, PRZ AS PREZIME, NVL(NAP, 'Ne rukovodi projektom') AS "NAZIV PROJEKTA" FROM RADNIK 
    LEFT OUTER JOIN PROJEKAT
    ON RADNIK.MBR = PROJEKAT.RUK;

-- PRIKAZATI MBR RADNIKA I NAZIVE SVIH PROJEKATA NA KOJIMA RADNICI RADE
-- UKOLIKO RADNIK NE RADI NI NA JEDNOM PROJEKTU NAPISATI 0 UMESTO MBR
SELECT PROJEKAT.SPR, NAP AS "NAZIV PROJEKTA", NVL(MBR, 0) FROM PROJEKAT 
    LEFT OUTER JOIN RADPROJ
    ON PROJEKAT.SPR = RADPROJ.SPR;

-- PRIKAZATI MBR RADNIKA I NAZIVE SVIH PROJEKATA NA KOJIMA RADNICI RADE
-- UKOLIKO RADNIK NE RADI NI NA JEDNOM PROJEKTU NAPISATI 0 UMESTO MBR
SELECT PROJEKAT.SPR, NAP AS "NAZIV PROJEKTA", NVL(MBR, 0) FROM PROJEKAT, RADPROJ
    WHERE PROJEKAT.SPR = RADPROJ.SPR(+);

-- PRIKAZATI ZA SVE RADNIKE I PROJEKTE NA KOJIMA RADE MBR, PRZ, IME, SPR I NAP.
-- ZA RADNIKE KOJI NE RADE NI NA JEDNOM PROJEKTU TREBA PRIKAZATI MBR, PRZ I IME
-- DOK ZA VREDNOSTI OBELEZJA SPR I NAP TREBA ZADATI REDOM KONSTANTE 0 I "NE POSTOJI"
-- SORTIRATI RASTUCE PO MBR
SELECT RADNIK.MBR, IME, PRZ AS PREZIME, NVL(RADPROJ.SPR, 0), NVL(PROJEKAT.NAP, 'NE POSTOJI') AS "NAZIV PROJEKTA" 
    FROM (RADNIK LEFT OUTER JOIN RADPROJ ON RADNIK.MBR = RADPROJ.MBR)
         LEFT OUTER JOIN PROJEKAT ON RADPROJ.SPR = PROJEKAT.SPR;

-- KATEGORISATI PRIMANJA I ISPISATI IH SORTIRANO
SELECT MBR, IME, PRZ AS PREZIME, PLT AS PLATA,
    CASE
        WHEN PLT < 10000 THEN 'MALA PRIMANJA'
        WHEN PLT >= 10000 AND PLT < 20000 THEN 'SREDNJA PRIMANJA'
        ELSE 'VISOKA PRIMANJA'
    END AS KATEGORIJA
FROM RADNIK
ORDER BY 
    CASE KATEGORIJA
        WHEN 'MALA PRIMANJA' THEN 1
        WHEN 'SREDNJA PRIMANJA' THEN 2
        ELSE 3
    END;