-- 1. PRIKAZATI PODATKE O KLIJENTIMA (IDK, IMEK, PRZK) SORTIRANE PO IMENU I PREZIMENU
SELECT IDK, IMEK, PRZK FROM KLIJENT
    ORDER BY IMEK, PRZK;

-- 2. PRIKAZATI SVE TIPOVE KREDITA (IDT, NAZT) GDE JE PROCENAT ZARADE BANKE IZMEDJU 2 I 10%
SELECT IDT, NAZT FROM TIPKREDITA
    WHERE PROCENAT BETWEEN 2 AND 10;

-- 3.
ALTER TABLE KLIJENT
 ADD CONSTRAINT GOD_CHECK CHECK (GOD > '1-JAN-1950');

INSERT INTO KLIJENT (IDK, IMEK, PRZK, GOD) VALUES (800, 'Nikola', 'Nikolic', '5-Jun-1940');

-- 4.
SELECT IDKR, NAZT, ODOBIZN, ((ODOBIZN * (1 + (PROCENAT / 100))) - ODOBIZN) AS PROFIT,
    CASE
        WHEN DRZISO = 'SRB' THEN 1
        WHEN DRZISO = 'ITA' THEN 2
        WHEN DRZISO = 'FRA' THEN 3
        WHEN DRZISO = 'AUT' THEN 4
        ELSE 5
    END AS SORT_DRZAVA,
    DRZISO
FROM KREDIT K, BANKA B, TIPKREDITA TK
    WHERE K.BANKA = B.IDB AND
    K.TIP = TK.IDT AND
    TK.NAZT != 'Gotovinski'
    ORDER BY SORT_DRZAVA;

-- 5. 
SELECT IMEK, PRZK, NAZB, NAZT, TRAZIZN, ODOBIZN FROM KREDIT K, KLIJENT K, BANKA B, TIPKREDITA TK
    WHERE K.KLIJENT = K.IDK AND
    K.BANKA = B.IDB AND
    K.TIP = TK.IDT AND
    K.ODOBIZN >= 0.95 * K.TRAZIZN;

-- 6.
SELECT DISTINCT KLIJENT FROM KREDIT K, BANKA B
    WHERE K.BANKA IN (SELECT IDB FROM BANKA WHERE NAZB = 'BancaIntesa')
    AND K.BANKA NOT IN (SELECT IDB FROM BANKA WHERE NAZB = 'Erste Bank')
    ;

SELECT *FROM KREDIT;

-- 7.
SELECT NAZB FROM KREDIT K, BANKA B
    WHERE K.BANKA = B.IDB
    GROUP BY K.BANKA, NAZB
    HAVING COUNT(KLIJENT) >= 2;

-- 8.
UPDATE KLIJENT 
    SET PRZK = PRZK || '*'
    WHERE GOD < '1-JAN-1970';

SELECT PRZK, GOD FROM KLIJENT;

-- 9.
CREATE OR REPLACE VIEW POGLED AS (SELECT NAZT, NVL(AVG(TRAZIZN), 0) AS PROSEK_TRAZIO, 
       NVL(AVG(ODOBIZN), 0) AS PROSEK_ODOBRENO, VAL,
    CASE
        WHEN VAL = 'USD' THEN 1
        WHEN VAL = 'EUR' THEN 2
        WHEN VAL = 'CHF' THEN 3
        ELSE 4
    END AS VALUTA
FROM KREDIT K, TIPKREDITA TK
    WHERE K.TIP = TK.IDT
    GROUP BY TIP, NAZT, VAL
    HAVING SUM(TRAZIZN) < 30000);

SELECT *FROM POGLED;

-- 10.
SELECT COUNT(KR.TRAZIZN) AS BROJ_KREDITA, SUM(KR.TRAZIZN) AS TRAZENO_KREDITA FROM KREDIT KR, KLIJENT K
    WHERE KR.KLIJENT = K.IDK AND
    GOD BETWEEN '1-JAN-1946' AND '1-JAN-1965'
    GROUP BY TRAZIZN
    HAVING SUM(TRAZIZN) > 9000
UNION
SELECT COUNT(KR.TRAZIZN) AS BROJ_KREDITA, SUM(KR.TRAZIZN) AS TRAZENO_KREDITA FROM KREDIT KR, KLIJENT K
    WHERE KR.KLIJENT = K.IDK AND
    GOD BETWEEN '1-JAN-1966' AND '1-JAN-1985'
    GROUP BY TRAZIZN
    HAVING SUM(TRAZIZN) > 9000
UNION
SELECT COUNT(KR.TRAZIZN) AS BROJ_KREDITA, SUM(KR.TRAZIZN) AS TRAZENO_KREDITA FROM KREDIT KR, KLIJENT K
    WHERE KR.KLIJENT = K.IDK AND
    GOD > '1-JAN-1986'
    GROUP BY TRAZIZN
    HAVING SUM(TRAZIZN) > 9000;