-- ZA SVAKOG RADNIKA PRONACI BROJ PROJEKATA NA KOJIMA RADI
SELECT MBR, COUNT(SPR) FROM RADPROJ
    GROUP BY MBR;

-- PRIKAZATI KOLIKO RADNIKA RADI NA SVAKOM PROJEKTU I KOLIKO JE
-- UKUPNO ANGAZOVANJE NA TOM PROJEKTU
SELECT SPR, COUNT(MBR) AS "BROJ RADNIKA NA PROJEKTU", 
       SUM(BRC) AS ANGAZOVANJE FROM RADPROJ
    GROUP BY SPR;

-- IZLISTATI MBR RADNIKA KOJI RADE NA VISE OD DVA PROJEKTA,
-- PORED MBR-A PRIKAZATI I BROJ PROJEKATA NA KOJIMA RADNICI RADE
SELECT MBR, COUNT(SPR) FROM RADPROJ
    GROUP BY MBR HAVING COUNT(SPR) > 2;

-- IZLISTATI RADNIKE KOJI RADE NA MAKAR JEDNOM PROJEKTU
SELECT *FROM RADPROJ WHERE MBR IN(SELECT MBR FROM RADPROJ);

-- IZLISTATI U RASTUCEM REDOSLEDU PLATE, MBR, IME, PRZ I PLT
-- RADNIKA KOJI IMAJU PLATU VECU OD PROSECNE
SELECT MBR, IME, PRZ AS PREZIME, PLT AS PLATA, 
    (SELECT ROUND(AVG(PLT), 0) FROM RADNIK) AS "PROSECNA PLATA" FROM RADNIK 
    WHERE PLT > (SELECT AVG(PLT) FROM RADNIK)
    ORDER BY PLT;

-- IZLISTATI MBR, IME, PRZ RADNIKA KOJI RADE NA PROJEKTU SA SIFROM 10,
-- A NE RADE NA PROJEKTU SA SIFROM 30
SELECT MBR, IME, PRZ AS PREZIME FROM RADNIK 
    WHERE MBR IN
        (SELECT MBR FROM RADPROJ WHERE SPR = 10) AND
        MBR NOT IN 
        (SELECT MBR FROM RADPROJ WHERE SPR = 30);

--IZLISTATI IME, PRZ, GOD, NAJSTARIJEG RADNIKA
SELECT IME, PRZ, GOD FROM RADNIK 
    WHERE GOD = (SELECT MIN(GOD) FROM RADNIK);

-- IZLISTATI IME, PRZ, GOD, NAJSTARIJEG RADNIKA
SELECT IME, PRZ, GOD FROM RADNIK 
    WHERE GOD <= ALL(SELECT GOD FROM RADNIK);

-- PRIKAZATI MBR, IME, PRZ, PLT KOJI RADE NA PROJEKTU SA SIFROM 10

SELECT RADPROJ.MBR, BRC, IME, PRZ, PLT FROM RADPROJ, RADNIK 
    WHERE (SPR = 10) AND (RADPROJ.MBR = RADNIK.MBR);

-- PRIKAZATI MBR, IME, PRZ, PLT RADNIKA KOJI SU RUKOVODIOCI PROJEKTA
SELECT DISTINCT RADNIK.MBR, IME, PRZ AS PREZIME, PLT AS PLATA FROM RADNIK, PROJEKAT
    WHERE RADNIK.MBR = PROJEKAT.RUK;

-- ISPISATI NAZIVE PROJEKATA NA KOJIMA RADE
-- RADNICI KOJI RADE I NA PROJEKTU SA SIFROM 60
SELECT NAP FROM PROJEKAT
    WHERE SPR IN (SELECT SPR FROM RADPROJ
    WHERE MBR IN (SELECT MBR FROM RADPROJ WHERE SPR = 60)
    );

-- ISPISATI NAZIVE PROJEKATA NA KOJIMA RADE
-- RADNICI KOJI RADE I NA PROJEKTU SA SIFROM 60
SELECT DISTINCT RADPROJ.SPR, NAP FROM RADPROJ, PROJEKAT
    WHERE MBR IN (SELECT MBR FROM RADPROJ WHERE SPR = 60) 
    AND RADPROJ.SPR = PROJEKAT.SPR;

-- PRIKAZATI IMENA I PREZIMENA RUKOVODILACA PROJEKATA I 
-- BROJ PROJEKATA NA KOJIMA RADE
SELECT RP.MBR, R.IME, R.PRZ AS PREZIME, COUNT(RP.SPR) FROM RADPROJ RP, RADNIK R
    WHERE (RP.MBR = R.MBR) AND
    (R.MBR IN (SELECT RUK FROM PROJEKAT))
    GROUP BY RP.MBR, R.IME, R.PRZ;

-- PRIKAZATI IMENA I PREZIMENA RUKOVODILACA PROJEKATA I 
-- BROJ PROJEKATA NA KOJIMA RADE
SELECT RUK, IME, PRZ AS PREZIME, COUNT(DISTINCT RP.SPR) AS "BROJ PROJEKATA"
    FROM PROJEKAT P, RADNIK R, RADPROJ RP
    WHERE (P.RUK = R.MBR) AND (RUK = RP.MBR)
    GROUP BY RUK, IME, PRZ;